Add moderation paragraph to README.md
gambe-ro/lobsters pull request #1
Opened 2019-03-18 10:27 UTC by riggraz

2019-03-21 21:28 UTC, chobeat requested changes

2019-03-21 21:28 UTC, chobeat commented on README.md
> +[gambe.ro](https://www.gambe.ro) is an italian lobste.rs clone. We aim to build a strong community of italian programmers where constructive discussions can take place.
clone mi sembra una parola inadatta. Piuttosto qualcosa tipo "is an italian community built using lobste.rs software".

2019-03-21 21:28 UTC, chobeat commented on README.md
> +Make sure you have Docker daemon running. Then:
magari metti un generico "Install Docker" con link al loro getting started

2019-03-21 21:28 UTC, chobeat commented on README.md
> +  */20 * * * * cd /path/to/journalduhacker && env RAILS_ENV=production bundle exec rake ts:index > /dev/null
ancora il vecchio path

2019-03-21 21:28 UTC, chobeat commented on README.md
> +Note: when moderating you should provide a moderation reason.
questa nota messa così è un po' volante. Io la toglierei, nel senso che l'interfaccia penso ti forzi a farlo

2019-03-22 08:32 UTC, PizzolatoDavide commented on README.md
> +Click the 'edit' button under the story title. You can:
```suggestion
By clicking the 'edit' button under the story title you can:
```
Collegerei le due frasi così.
Mi sembra più chiaro.

2019-03-22 08:36 UTC, PizzolatoDavide commented on README.md
> +story.save
```suggestion
story.save()
```
In ruby sintatticamente è corretto ma per coerenza con story.delete() scritto sotto e per leggibilità metterei le parentesi tonde.

2019-03-24 08:25 UTC, chobeat approved these changes

2019-03-25 07:16 UTC, pizzo00 approved these changes

2019-03-25 19:41 UTC, merged