Mysql backup script
gambe-ro/lobsters pull request #7
Opened 2019-03-28 20:47 UTC by PizzolatoDavide

2019-03-28 20:53 UTC, PizzolatoDavide commented
E' scritto in Python 3 e utilizza la libreria [ruamel.yaml](http://yaml.readthedocs.io)

2019-03-29 16:35 UTC, CapacitorSet requested changes
Dal punto di vista del codice la mia review è questa.

Da un punto di vista più generale mi sembra di capire che il codice che c'è ora (quindi senza lettura del db e senza upload) stia essenzialmente reinventando la ruota: fa a mano quello che si chiama rotation, e che viene svolto egregiamente da `logrotate` (con l'ipotesi che il backup si faccia su Linux/BSD). Mi spiace buttare via il tuo lavoro finora, ma sono dell'opinione che questo lavoro vada svolto con una config per `logrotate` (che peraltro consentirebbe di aggiungere feature interessanti come la compressione dei file) e che lo script si debba occupare solo di tirare giù il dump dal db e sincronizzare i file con FTP.

2019-03-29 16:35 UTC, CapacitorSet commented on script/db_backup/config.yml
> +db_user: user
In YAML è più elegante usare il nesting "nativo":

```yaml
db:
    user: user
    password: pass
```

Idem per le altre chiavi.

2019-03-29 16:35 UTC, CapacitorSet commented on script/db_backup/db_backup.py
> +BUFFER_INDEX_PATH = '.\\db_backup_buffer_index.txt'
Il backslash nei path funziona solo su Windows, credo.

2019-03-29 16:35 UTC, CapacitorSet commented on script/db_backup/db_backup.py
> +    backup_file = []
```python
backup_file = [f for f in all_file if f.startswith('DatabaseBackup_')]
```

2019-04-01 10:42 UTC, PizzolatoDavide commented
> Dal punto di vista del codice la mia review è questa.
> 
> Da un punto di vista più generale mi sembra di capire che il codice che c'è ora (quindi senza lettura del db e senza upload) stia essenzialmente reinventando la ruota: fa a mano quello che si chiama rotation, e che viene svolto egregiamente da `logrotate` (con l'ipotesi che il backup si faccia su Linux/BSD). Mi spiace buttare via il tuo lavoro finora, ma sono dell'opinione che questo lavoro vada svolto con una config per `logrotate` (che peraltro consentirebbe di aggiungere feature interessanti come la compressione dei file) e che lo script si debba occupare solo di tirare giù il dump dal db e sincronizzare i file con FTP.

Riscrive il file rotanting si è reso necessario per poter gestire i file su server ftp.
In locale potremmo senza problemi usare sistemi come quello descritto da te ma se vogliamo il mirroring su ftp dobbiamo gestire i file a mano e in entrambi i supporti allo stesso modo.

2019-04-10 07:23 UTC, closed without merging

2019-04-10 07:23 UTC, PizzolatoDavide commented
mysqldump -u user -p --all-databases | gzip -9 > backup.sql

2019-04-10 07:35 UTC, CapacitorSet commented
La rotation si fa a mano o che?

2019-04-10 10:31 UTC, PizzolatoDavide commented
Come hai proposto tu useremo logrotate con la seguente configurazione:

```
/var/backup_db/backup.sql.gz
{
     daily
     rotate 10
     nocompress
     extension .qz
     dateext
     dateformat .%Y-%m-%d
     dateyesterday
     postrotate
         bakup_script.sh
     endscript
}
```