Night mode home page (#90)
gambe-ro/lobsters pull request #91
Opened 2019-12-12 10:02 UTC by chobeat

* moved switch to home page

* added style

2019-12-12 10:24 UTC, CapacitorSet commented
Ti faccio la review a mano, ché da cellulare non sembra si possa farla in modo fancy.

Tutto ok, solo nel primo file non mi torna quel "require jquery". È utile?

2019-12-12 13:13 UTC, chobeat commented
Allora, siccome quando l'utente non è loggato non importiamo il file js grosso (dove c'è un altro require per jquery) ma solo il file col night mode, ho un doppio import per coprire sia il caso in cui è loggato sia il caso in cui non lo sia.

2019-12-12 16:39 UTC, CapacitorSet commented
Non è bellissimo però far tirare dentro tutto jQuery agli utenti sloggati solo per un toggle, io piuttosto riscriverei quei due utilizzi di jQuery in vanilla JS.

Fix:

```js
// 1
document.getElementById("fs").checked = night_mode
// 2: $(document).ready(function() {
document.addEventListener("DOMContentLoaded", function() {
// 3
document.getElementById("fs").onready = function() {
```

2019-12-14 12:37 UTC, chobeat commented
fixed

2019-12-14 12:58 UTC, CapacitorSet requested changes

2019-12-14 12:58 UTC, CapacitorSet commented on app/views/layouts/application.html.erb
> +          <span class="tema_scuro">Tema Scuro:
`Tema Scuro` -> `Tema scuro`

2019-12-14 12:58 UTC, CapacitorSet commented on app/views/layouts/application.html.erb
> +                <label class="night_switch_label" for="fs">
Questa label serve? A occhio non è usata da nessuna parte.

2019-12-14 12:58 UTC, CapacitorSet commented on app/views/layouts/application.html.erb
> +          <input type="checkbox" name="night_switch" id="fs" class="night_switch" checked>
È opportuno che sia checked di default? Inoltre non serve che abbia un `name` perchè non va submittata.

2019-12-14 12:58 UTC, CapacitorSet commented on app/views/layouts/application.html.erb
> + <%= javascript_include_tag "night_mode" %>
È il caso di lasciare un commento sul perché mettiamo la night mode nell'else, ché visto così sembra che la night mode sia abilitata solo se sei sloggato.

2019-12-14 12:58 UTC, CapacitorSet commented on app/views/layouts/application.html.erb
> +          <input type="checkbox" name="night_switch" id="fs" class="night_switch" checked>
\+ il nome "fs" aveva senso quando si chiamava flipswitch, ora diamogli un nome più descrittivo

2019-12-14 12:59 UTC, CapacitorSet commented on app/views/layouts/application.html.erb
> +                <label class="night_switch_label" for="fs">
Anzi, semanticamente sarebbe corretto che sia la label a contenere "Tema scuro", tipo `<label class="tema_scuro">Tema scuro:` etc

2019-12-22 21:47 UTC, CapacitorSet approved these changes
È rimasta la maiuscola su Tema Scuro, complessivamente lgtm

2019-12-22 21:50 UTC, merged